# Generated by Django 5.1.6 on 2025-03-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
